version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py migrate --run-syncdb  &&python manage.py runserver 0.0.0.0:8000"
    container_name: Django-Vendor-Management-System
    volumes:
      - .:/Django-Vendor-Management-System
    ports:
      - "8000:8000"